alter table public.user_tenant_preferences
  add column if not exists visualization_theme_id text
  check (
    visualization_theme_id is null
    or visualization_theme_id in ('lime', 'cyan', 'amber', 'royal', 'spectrum')
  );

create table public.org_review_applications (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.tenants (id) on delete cascade,
  org_no text not null check (length(trim(org_no)) > 0),
  org_name text not null check (length(trim(org_name)) > 0),
  review_status text not null check (review_status in ('pending', 'approved', 'rejected')),
  remark text not null default '',
  in_library text not null check (in_library in ('in', 'out')),
  semester text not null default '2025-2026-1',
  contact text not null default '',
  phone text not null default '',
  address text not null default '',
  detail jsonb not null default '{}'::jsonb check (jsonb_typeof(detail) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, org_no)
);

create index org_review_applications_tenant_status_idx
  on public.org_review_applications (tenant_id, review_status);
create index org_review_applications_tenant_semester_idx
  on public.org_review_applications (tenant_id, semester);
create index org_review_applications_tenant_name_idx
  on public.org_review_applications (tenant_id, org_name);

create table public.gate_device_groups (
  tenant_id text not null references public.tenants (id) on delete cascade,
  id text not null check (length(trim(id)) > 0),
  parent_id text,
  name text not null check (length(trim(name)) > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  foreign key (tenant_id, parent_id)
    references public.gate_device_groups (tenant_id, id)
    on delete cascade
    deferrable initially deferred
);

create index gate_device_groups_tenant_parent_sort_idx
  on public.gate_device_groups (tenant_id, parent_id, sort_order);

create table public.gate_devices (
  tenant_id text not null references public.tenants (id) on delete cascade,
  id bigint generated by default as identity,
  name text not null check (length(trim(name)) > 0),
  channel_type text not null check (channel_type in ('dual', 'single')),
  status_key text not null check (status_key in ('online', 'offline', 'running')),
  status_label text not null check (length(trim(status_label)) > 0),
  code text not null check (length(trim(code)) > 0),
  location text not null default '',
  group_id text not null,
  sub_info jsonb not null default '[]'::jsonb check (jsonb_typeof(sub_info) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  unique (tenant_id, code),
  foreign key (tenant_id, group_id)
    references public.gate_device_groups (tenant_id, id)
    on delete restrict
);

create index gate_devices_tenant_group_idx
  on public.gate_devices (tenant_id, group_id);
create index gate_devices_tenant_status_idx
  on public.gate_devices (tenant_id, status_key);
create index gate_devices_tenant_name_idx
  on public.gate_devices (tenant_id, name);

create trigger org_review_applications_set_updated_at
before update on public.org_review_applications
for each row execute function private.set_updated_at();

create trigger gate_device_groups_set_updated_at
before update on public.gate_device_groups
for each row execute function private.set_updated_at();

create trigger gate_devices_set_updated_at
before update on public.gate_devices
for each row execute function private.set_updated_at();

alter table public.org_review_applications enable row level security;
alter table public.gate_device_groups enable row level security;
alter table public.gate_devices enable row level security;

create policy org_review_applications_select on public.org_review_applications
for select to authenticated
using ((select private.is_tenant_member(tenant_id)) or (select private.is_platform_admin()));

create policy org_review_applications_write on public.org_review_applications
for all to authenticated
using ((select private.is_tenant_admin(tenant_id)) or (select private.is_platform_admin()))
with check ((select private.is_tenant_admin(tenant_id)) or (select private.is_platform_admin()));

create policy gate_device_groups_select on public.gate_device_groups
for select to authenticated
using ((select private.is_tenant_member(tenant_id)) or (select private.is_platform_admin()));

create policy gate_device_groups_write on public.gate_device_groups
for all to authenticated
using ((select private.is_tenant_admin(tenant_id)) or (select private.is_platform_admin()))
with check ((select private.is_tenant_admin(tenant_id)) or (select private.is_platform_admin()));

create policy gate_devices_select on public.gate_devices
for select to authenticated
using ((select private.is_tenant_member(tenant_id)) or (select private.is_platform_admin()));

create policy gate_devices_write on public.gate_devices
for all to authenticated
using ((select private.is_tenant_admin(tenant_id)) or (select private.is_platform_admin()))
with check ((select private.is_tenant_admin(tenant_id)) or (select private.is_platform_admin()));

grant select, insert, update, delete on public.org_review_applications to authenticated;
grant select, insert, update, delete on public.gate_device_groups to authenticated;
grant select, insert, update, delete on public.gate_devices to authenticated;
grant usage, select on sequence public.org_review_applications_id_seq to authenticated;
grant usage, select on sequence public.gate_devices_id_seq to authenticated;

grant select, insert, update, delete on public.org_review_applications to service_role;
grant select, insert, update, delete on public.gate_device_groups to service_role;
grant select, insert, update, delete on public.gate_devices to service_role;
grant usage, select on sequence public.org_review_applications_id_seq to service_role;
grant usage, select on sequence public.gate_devices_id_seq to service_role;

insert into public.org_review_applications (
  id, tenant_id, org_no, org_name, review_status, remark, in_library,
  semester, contact, phone, address
)
select seed.*
from (
  values
    (1::bigint, 'bureau-001', '20481939391450', '广州星光艺术培训中心', 'pending', '材料完整，符合标准', 'in', '2025-2026-1', '陈远远', '13928373920', '天河区体育西路103号'),
    (2, 'bureau-001', '20481939391451', '深圳未来教育科技有限公司', 'rejected', '资质证书已过期', 'out', '2025-2026-1', '李明辉', '13847288392', '南山区科技园南路18号'),
    (3, 'bureau-001', '20481939391452', '东莞博雅文化传播有限公司', 'approved', '审核通过，材料齐全', 'in', '2025-2026-1', '王思琪', '13758922947', '莞城区东城大道56号'),
    (4, 'bureau-001', '20481939391453', '佛山启航体育发展有限公司', 'rejected', '消防设施需更新', 'out', '2025-2026-1', '张伟强', '13667398573', '禅城区季华五路33号'),
    (5, 'bureau-001', '20481939391454', '珠海蓝天少儿编程教育', 'pending', '教师资格待验证', 'out', '2025-2026-1', '刘晓燕', '13589372759', '香洲区人民东路228号'),
    (6, 'bureau-001', '20481939391455', '中山绿叶营养健康管理中心', 'rejected', '食谱需营养师审核', 'out', '2025-2026-1', '赵国栋', '13475938642', '石岐区中山路168号'),
    (7, 'bureau-001', '20481939391456', '惠州阳光心理咨询服务中心', 'approved', '场地合格，人员齐备', 'in', '2025-2026-1', '孙丽华', '13395739571', '惠城区麦地路12号'),
    (8, 'bureau-001', '20481939391457', '江门新世纪外语培训学校', 'rejected', '保险单据缺失', 'out', '2025-2026-1', '周建国', '13285733864', '蓬江区建设路88号'),
    (9, 'bureau-001', '20481939391458', '肇庆智慧树早教中心', 'pending', '收费标准需公示', 'out', '2025-2026-1', '吴秀英', '13147855927', '端州区天宁北路45号'),
    (10, 'bureau-001', '20481939391459', '清远翰林书画院', 'rejected', '合同范本待备案', 'out', '2025-2026-1', '郑志豪', '13058922648', '清城区先锋路22号'),
    (11, 'bureau-001', '20481939391460', '汕头海韵音乐培训学校', 'pending', '等待场地验收', 'out', '2025-2026-1', '林海涛', '13612345678', '金平区长平路156号'),
    (12, 'bureau-001', '20481939391461', '湛江阳光舞蹈艺术中心', 'approved', '资质齐全，通过审核', 'in', '2025-2026-1', '黄美玲', '13723456789', '赤坎区南桥北路78号'),
    (13, 'bureau-001', '20481939391462', '茂名启智教育咨询有限公司', 'rejected', '师资证明材料不全', 'out', '2025-2026-1', '何志明', '13834567890', '茂南区油城五路12号'),
    (14, 'bureau-001', '20481939391463', '梅州客家文化研学基地', 'pending', '待补充营业执照副本', 'out', '2025-2026-1', '钟文华', '13945678901', '梅江区江南路99号'),
    (15, 'bureau-001', '20481939391464', '韶关丹霞户外拓展中心', 'approved', '安全设施达标', 'in', '2025-2026-1', '曾国平', '13056789012', '浈江区风度北路36号'),
    (16, 'bureau-001', '20481939391465', '河源万绿湖生态教育基地', 'pending', '环评报告待提交', 'out', '2025-2026-1', '谢春花', '13167890123', '源城区河源大道128号'),
    (17, 'bureau-001', '20481939391466', '阳江海陵岛研学旅行社', 'rejected', '旅行社资质已过期', 'out', '2025-2026-1', '陈海洋', '13278901234', '江城区安宁路55号'),
    (18, 'bureau-001', '20481939391467', '揭阳榕城书法培训中心', 'approved', '教师资格证齐全', 'in', '2025-2026-1', '林书豪', '13389012345', '榕城区临江北路77号'),
    (19, 'bureau-001', '20481939391468', '潮州陶瓷艺术工作室', 'pending', '作品展示区待验收', 'in', '2025-2026-1', '蔡艺文', '13490123456', '湘桥区太平路188号'),
    (20, 'bureau-001', '20481939391469', '云浮新兴禅文化体验馆', 'rejected', '消防通道被占用', 'out', '2025-2026-1', '罗禅心', '13501234567', '云城区云城大道66号'),
    (21, 'bureau-001', '20481939391470', '番禺大石少儿美术馆', 'approved', '设施完善，通过审核', 'in', '2025-2026-1', '方小敏', '13612340001', '番禺区大石街道富丽路8号'),
    (22, 'bureau-001', '20481939391471', '花都狮岭皮具设计学院', 'pending', '办学许可证待更新', 'out', '2025-2026-1', '杨皮匠', '13723450002', '花都区狮岭镇阳光路12号'),
    (23, 'bureau-001', '20481939391472', '增城荔枝湾自然教育营地', 'rejected', '户外场地安全隐患', 'out', '2025-2026-1', '廖荔红', '13834560003', '增城区荔城街道荔乡路56号'),
    (24, 'bureau-001', '20481939391473', '从化温泉康养研学中心', 'approved', '卫生许可证有效', 'in', '2025-2026-1', '温泉生', '13945670004', '从化区温泉镇温泉东路99号'),
    (25, 'bureau-001', '20481939391474', '南沙湿地生态科普基地', 'pending', '科普资质待审批', 'out', '2025-2026-1', '何湿地', '13056780005', '南沙区万顷沙镇新港大道1号'),
    (26, 'bureau-001', '20481939391475', '白云机场航空体验教育中心', 'approved', '合作协议已签署', 'in', '2025-2026-1', '蓝天飞', '13167890006', '白云区人和镇机场路168号'),
    (27, 'bureau-001', '20481939391476', '黄埔军事素质拓展训练营', 'rejected', '教官资质证明缺失', 'out', '2025-2026-1', '吴铁军', '13278900007', '黄埔区长洲岛军校路1号'),
    (28, 'bureau-001', '20481939391477', '越秀北京路非遗传承工坊', 'pending', '非遗传承人认证中', 'in', '2025-2026-1', '古传承', '13389010008', '越秀区北京路步行街218号'),
    (29, 'bureau-001', '20481939391478', '荔湾西关粤剧培训社', 'approved', '文化部门已备案', 'in', '2025-2026-1', '粤韵声', '13490120009', '荔湾区恩宁路永庆坊3号'),
    (30, 'bureau-001', '20481939391479', '海珠琶洲数字创意学院', 'rejected', '办公场地租赁合同到期', 'out', '2025-2026-1', '数码通', '13501230010', '海珠区琶洲大道东1号')
) as seed(id, tenant_id, org_no, org_name, review_status, remark, in_library, semester, contact, phone, address)
where exists (select 1 from public.tenants where id = seed.tenant_id)
on conflict (tenant_id, org_no) do nothing;

update public.org_review_applications
set detail = jsonb_build_object(
  'hasChange', true,
  'avatar', 'https://via.placeholder.com/130/1a1a1a/ff6600?text=🔥',
  'region', '广东省 广州市 花都区',
  'legalPerson', '李国平',
  'creditCode', '91440101MMAMA9Y82773',
  'licenseNo', '14408493929249',
  'website', 'https://www.wasag.com',
  'businessScope', 'K-12课外辅导，素质教育',
  'licenseValidRange', '2025-05-20 至 2028-12-12',
  'licenseImages', jsonb_build_array(
    'https://via.placeholder.com/100/fafafa/999?text=许可证1',
    'https://via.placeholder.com/100/fafafa/999?text=许可证2',
    'https://via.placeholder.com/100/fafafa/999?text=许可证3'
  ),
  'businessValidRange', '2025-05-20 至 2028-12-12',
  'businessImages', jsonb_build_array(
    'https://via.placeholder.com/100/fafafa/999?text=执照1',
    'https://via.placeholder.com/100/fafafa/999?text=执照2',
    'https://via.placeholder.com/100/fafafa/999?text=执照3'
  ),
  'idCardFront', 'https://via.placeholder.com/285x176/fafafa/999?text=国徽面',
  'idCardBack', 'https://via.placeholder.com/285x176/fafafa/999?text=人像面',
  'commitmentImages', jsonb_build_array(
    'https://via.placeholder.com/100/fafafa/999?text=承诺书1',
    'https://via.placeholder.com/100/fafafa/999?text=承诺书2',
    'https://via.placeholder.com/100/fafafa/999?text=承诺书3'
  )
)
where tenant_id = 'bureau-001'
  and detail = '{}'::jsonb;

select setval(
  pg_get_serial_sequence('public.org_review_applications', 'id'),
  greatest(coalesce((select max(id) from public.org_review_applications), 1), 1),
  true
);

insert into public.gate_device_groups (tenant_id, id, parent_id, name, sort_order)
select seed.*
from (
  values
    ('school-001', 'all', null::text, '全部设备', 0),
    ('school-001', 'gate', 'all', '校门口', 0),
    ('school-001', 'main-gate', 'gate', '正门', 0),
    ('school-001', 'side-gate', 'gate', '侧门', 1),
    ('school-001', 'canteen', 'all', '食堂', 1),
    ('school-001', 'dorm', 'all', '宿舍', 2),
    ('school-001', 'more', 'all', '更多', 3)
) as seed(tenant_id, id, parent_id, name, sort_order)
where exists (select 1 from public.tenants where id = seed.tenant_id)
on conflict (tenant_id, id) do nothing;

insert into public.gate_devices (
  tenant_id, id, name, channel_type, status_key, status_label,
  code, location, group_id, sub_info
)
select
  seed.tenant_id,
  seed.id,
  seed.name,
  seed.channel_type,
  seed.status_key,
  seed.status_label,
  seed.code,
  seed.location,
  seed.group_id,
  seed.sub_info::jsonb
from (
  values
    ('school-001', 1::bigint, '校正门-人脸闸机1', 'dual', 'online', '在线', 'G001-MAIN-01', '校正面左侧', 'main-gate', '[{"group":"测试A组","timezone":"固定全天通行"}]'),
    ('school-001', 2, '校正门-人脸闸机6', 'single', 'online', '在线', 'G001-SIDE-02', '校正面右侧', 'side-gate', '[{"group":"测试B组","timezone":"晚上通行"}]'),
    ('school-001', 3, '校正门-人脸闸机5', 'dual', 'offline', '离线', 'G001-MAIN-05', '正门内测', 'main-gate', '[{"group":"测试A组","timezone":"早班时区"}]'),
    ('school-001', 4, '校正门-人脸闸机3', 'dual', 'online', '在线', 'G001-MAIN-03', '正门北柱', 'all', '[{"group":"测试C组","timezone":"特定通道时区"}]'),
    ('school-001', 5, '食堂人脸闸机4', 'single', 'online', '在线', 'C002-DOOR-01', '食堂侧门', 'canteen', '[{"group":"后勤组","timezone":"就餐时段通行"}]'),
    ('school-001', 6, '树木园围墙闸机1', 'dual', 'online', '在线', 'G002-SIDE-01', '后山入口', 'all', '[{"group":"巡逻组","timezone":"特定工作时段"}]'),
    ('school-001', 7, '后门通道闸机3', 'single', 'offline', '离线', 'G003-BACK-03', '北门后墙', 'all', '[{"group":"维保组","timezone":"维保测试时段"}]'),
    ('school-001', 8, '宿舍闸机1', 'single', 'online', '在线', 'D003-MAIN-01', '宿舍A座', 'dorm', '[{"group":"宿管组","timezone":"查寝通行时段"}]'),
    ('school-001', 9, '宿舍闸机2', 'dual', 'online', '在线', 'D003-MAIN-02', '宿舍B座', 'dorm', '[{"group":"学生组","timezone":"归寝限制时段"}]'),
    ('school-001', 10, '体育馆人脸主入口', 'dual', 'online', '在线', 'S004-MAIN-01', '体育馆正门', 'all', '[{"group":"学生组","timezone":"课程及自由时间"}]')
) as seed(tenant_id, id, name, channel_type, status_key, status_label, code, location, group_id, sub_info)
where exists (select 1 from public.tenants where id = seed.tenant_id)
on conflict (tenant_id, code) do nothing;

select setval(
  pg_get_serial_sequence('public.gate_devices', 'id'),
  greatest(coalesce((select max(id) from public.gate_devices), 1), 1),
  true
);
